import { useEffect, useMemo, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useParams, useSearchParams } from 'react-router-dom'
import { CATEGORIES, products, product as getProduct, money } from './data'

const Arrow = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" /></svg>
const Bag = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M5 8h14l-1 12H6L5 8Zm4 0V6a3 3 0 0 1 6 0v2" /></svg>

function Logo() { return <Link className="brand" to="/" aria-label="Harmornie Haven Bedding home"><img src="/images/logo.jpg" alt="Harmornie Haven Bedding" /><span>Harmornie Haven <small>BEDDING</small></span></Link> }

function App() {
  const [bag, setBag] = useState([])
  const [bagOpen, setBagOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const location = useLocation()
  useEffect(() => { setMenuOpen(false); window.scrollTo(0, 0) }, [location.pathname])
  useEffect(() => { document.body.classList.toggle('no-scroll', bagOpen); return () => document.body.classList.remove('no-scroll') }, [bagOpen])
  useEffect(() => { const onKey = (event) => { if (event.key === 'Escape') { setBagOpen(false); setMenuOpen(false) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  const add = (item) => { setBag((current) => [...current, item]); setBagOpen(true) }
  const total = bag.reduce((sum, item) => sum + item.price, 0)
  return <>
    <a className="skip-link" href="#main-content">Skip to content</a>
    <div className="announcement">Harmornie Haven Bedding · Est. 2021</div>
    <header className="site-header"><div className="header-inner"><Logo /><nav className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation"><NavLink to="/shop">Shop beds</NavLink><NavLink to="/about">Our story</NavLink><NavLink to="/contact">Enquiries</NavLink></nav><div className="header-actions"><button className="bag-toggle" onClick={() => setBagOpen(true)} aria-label={`Open saved beds, ${bag.length} items`}><Bag /><span>{bag.length}</span></button><button className="menu-toggle" onClick={() => setMenuOpen((open) => !open)} aria-expanded={menuOpen} aria-label="Toggle menu">{menuOpen ? 'Close' : 'Menu'}</button></div></div></header>
    <main id="main-content"><Routes><Route path="/" element={<Home add={add} />} /><Route path="/shop" element={<Shop add={add} />} /><Route path="/product/:id" element={<Product add={add} />} /><Route path="/about" element={<About />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} /></Routes></main>
    <Footer />
    <div className={bagOpen ? 'scrim on' : 'scrim'} onClick={() => setBagOpen(false)} />
    <aside className={bagOpen ? 'bag-panel open' : 'bag-panel'} aria-label="Saved beds" aria-hidden={!bagOpen}><div className="bag-head"><div><span className="eyebrow">YOUR SELECTION</span><h2>Saved beds</h2></div><button onClick={() => setBagOpen(false)} aria-label="Close saved beds">×</button></div><div className="bag-items">{bag.length ? bag.map((item, index) => <div className="bag-row" key={`${item.id}-${index}`}><img src={item.img} alt="" /><div><b>{item.name}</b><span>{money(item.price)}</span><button onClick={() => setBag((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div></div>) : <div className="bag-empty"><p>No beds saved yet.</p><Link className="button dark" to="/shop" onClick={() => setBagOpen(false)}>Explore the collection <Arrow /></Link></div>}</div>{bag.length > 0 && <div className="bag-foot"><div><span>Listed total</span><b>{money(total)}</b></div><p>This selection is for browsing. Online checkout is not available yet.</p><Link to="/contact" onClick={() => setBagOpen(false)} className="button dark">Enquire about a bed <Arrow /></Link></div>}</aside>
  </>
}

function Home({ add }) { return <><section className="hero"><div className="hero-copy"><h1>The bed you <em>come home to.</em></h1><p>Explore double and queen beds in spring and compressed foam. Compare real photos, finishes and prices.</p><Link className="button dark" to="/shop">Shop all beds <Arrow /></Link></div><div className="hero-visual"><img src="/images/queen-spring-pillowtop.jpg" alt="Queen-size spring pillowtop bed from Harmornie Haven" /></div></section><section className="brand-band section-shell"><div className="brand-band-logo"><img src="/images/logo.jpg" alt="Harmornie Haven Bedding logo, established 2021" /></div><div className="brand-band-copy"><h2>The name behind the beds.</h2><p>Harmornie Haven Bedding · Established 2021</p></div><div className="brand-band-details"><span>Spring & compressed foam</span><span>Standard & pillowtop</span><span>Double & queen</span></div></section><section className="collection section-shell"><div className="section-heading"><div><h2>A bed for <em>every room.</em></h2><p>Compare our photographed range by construction, size and finish.</p></div><Link className="text-link" to="/shop">View all eight beds <Arrow /></Link></div><div className="product-grid">{products.slice(0, 4).map((item) => <ProductCard key={item.id} item={item} add={add} />)}</div></section><section className="feature"><div className="feature-photo"><img src="/images/double-spring-pillowtop.jpg" alt="Double spring pillowtop bed" /></div><div className="feature-copy"><h2>An extra layer of <em>comfort.</em></h2><p>Like a softer finish? Explore our pillowtop models in spring and compressed foam constructions.</p><Link className="button outline" to="/shop?cat=pillowtop">See pillowtop beds <Arrow /></Link></div></section><section className="last-cta section-shell"><h2>Which bed feels <em>right for you?</em></h2><p>Browse the full range and note the model that interests you.</p><Link className="button dark" to="/shop">Explore the beds <Arrow /></Link></section></> }

function ProductCard({ item, add }) { return <article className="product-card"><Link className="product-image" to={`/product/${item.id}`}><img loading="lazy" src={item.img} alt={item.name} /></Link><div className="product-info"><span>{item.size} · {item.construction}</span><h3><Link to={`/product/${item.id}`}>{item.name}</Link></h3><div className="product-bottom"><strong>{money(item.price)}</strong><button onClick={() => add(item)} aria-label={`Save ${item.name}`}>Save <span>＋</span></button></div></div></article> }

function Shop({ add }) { const [params, setParams] = useSearchParams(); const [sort, setSort] = useState('featured'); const category = params.get('cat') || 'all'; const items = useMemo(() => { const filtered = products.filter((item) => category === 'all' || (category === 'spring' && item.construction === 'Spring') || (category === 'foam' && item.construction === 'Compressed foam') || (category === 'pillowtop' && item.finish === 'Pillowtop')); if (sort === 'low') filtered.sort((a,b) => a.price-b.price); if (sort === 'high') filtered.sort((a,b) => b.price-a.price); return filtered }, [category, sort]); return <section className="shop-page section-shell page-pad"><div className="page-intro"><h1>Explore the <em>beds.</em></h1><p>Eight beds. Two sizes. Spring or compressed foam, with standard and pillowtop finishes.</p></div><div className="shop-toolbar"><div className="chips" aria-label="Filter beds">{CATEGORIES.map((item) => <button key={item.id} className={category === item.id ? 'active' : ''} onClick={() => setParams(item.id === 'all' ? {} : { cat: item.id })}>{item.name}</button>)}</div><label>Sort <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><p className="result-count">Showing {items.length} {items.length === 1 ? 'bed' : 'beds'}</p><div className="product-grid">{items.map((item) => <ProductCard key={item.id} item={item} add={add} />)}</div></section> }

function Product({ add }) { const { id } = useParams(); const item = getProduct(id); if (!item) return <NotFound />; return <section className="pdp section-shell page-pad"><div className="pdp-photo"><img src={item.img} alt={item.name} /></div><div className="pdp-copy"><Link className="back-link" to="/shop">← All beds</Link><h1>{item.name}</h1><strong className="pdp-price">{money(item.price)}</strong><p>A {item.size.toLowerCase()}-size {item.construction.toLowerCase()} bed with a {item.finish.toLowerCase()} finish, shown in an original Harmornie Haven product photo.</p><dl><div><dt>Size</dt><dd>{item.size}</dd></div><div><dt>Construction</dt><dd>{item.construction}</dd></div><div><dt>Finish</dt><dd>{item.finish}</dd></div></dl><button className="button dark" onClick={() => add(item)}>Save this bed <Bag /></button><small>Contact details and ordering options will be added when confirmed by Harmornie Haven.</small></div></section> }

function About() { return <section className="about-page section-shell page-pad"><div><h1>About Harmornie <em>Haven.</em></h1><p>Established in 2021, Harmornie Haven Bedding focuses on beds. This site shows the real spring and compressed foam models provided by the company, in double and queen sizes.</p><Link className="button dark" to="/shop">Browse the beds <Arrow /></Link></div><img src="/images/double-compressed-standard.jpg" alt="Double compressed foam standard bed" /></section> }
function Contact() { return <section className="contact-page section-shell page-pad"><h1>Ask about a <em>bed.</em></h1><p>Interested in a model? Make a note of its name and price from the collection. Contact information and ordering details will be added when confirmed by Harmornie Haven.</p><Link className="button dark" to="/shop">Back to the collection <Arrow /></Link></section> }
function NotFound() { return <section className="not-found section-shell page-pad"><h1>That page isn’t here.</h1><p>Find your way back to the beds.</p><Link className="button dark" to="/shop">Shop beds <Arrow /></Link></section> }
function Footer() { return <footer className="footer"><div className="section-shell footer-main"><div><Logo /><p>Beds made for better rest.</p></div><nav aria-label="Footer navigation"><Link to="/shop">Shop beds</Link><Link to="/about">Our story</Link><Link to="/contact">Enquiries</Link></nav></div><div className="section-shell footer-bottom"><span>© 2026 Harmornie Haven Bedding</span><span>Est. 2021</span></div></footer> }
export default App
